### ISSUE TITLE
KeyError via collect_dependencies

### ISSUE THREAD

**Issue by almostssh** [bneijt/poetry-lock-package#18]
I ran into an edge case where poetry dependency name within `pyproject.tml` is different than the lock package `name` variable. This causes `collect_dependencies` to raise `KeyError: "Could not find 'pybluez' in lock file"`.

The toml is:
```
pybluez = {git = "https://github.com/pybluez/pybluez.git", rev = "d7f36702bba2abc8ea41977b2eea56a17431ac6d"}
```

Which produced a lock file with:
```
[[package]]
name = "PyBluez"
version = "0.30"
description = ""
category = "main"
optional = false
python-versions = ">=3.5"
develop = false

[package.extras]
ble = ["gattlib"]

[package.source]
type = "git"
url = "https://github.com/pybluez/pybluez.git"
reference = "d7f36702bba2abc8ea41977b2eea56a17431ac6d"
resolved_reference = "d7f36702bba2abc8ea41977b2eea56a17431ac6d"
```

I patched `read_lock_information` and `clean_dependencies` to return the correct name which produced `[tool.poetry.dependencies.PyBluez]` but `poetry build` still failed.

I started using your tool for multistage docker builds.

**Comment by bneijt** [comment]
Hi,

First of all, thank you for trying out `poetry-lock-package` and posting an issue when it failed.

There are multiple issues here, all bugs that I will have to address:
- The package name matching fails due to casing.  Work-around is using `PyBluez` in your `pyproject.toml`.
- The git reference is not used, but the version of `PyBluez`. I'm actually not sure what would be the preferred way to deal with this: add a depenency link to reference git or just use the version as it does now?
- The `develop` attribute of the lock is copied to the `pyproject.toml` file of the lock-package, which is not a valid configuration.

I'll start writing a patch, but would love to hear your ideas about what should end up in pyproject.toml for PyBluez: the git reference or the version number mentioned in the lock file?

**Comment by almostssh** [comment]
Mainly this is an issue because of PyBluez. I use git because the pip wheel has poetry [issue 3415](https://github.com/python-poetry/poetry/issues/3415). I chose the specific *rev* in order to freeze my requirements on a copy that works with poetry.

Unfortunately, the problem extends a little further than just renaming it in the toml file. PyBluez is a requirement for `bthci = "^0.0.19"`, I put it in the toml file so `btchi` builds properly with poetry. So renaming it in the toml fixes the first iteration but no the recursive iterations, so KeyError is raised again.

The real fix is for a new pip release of PyBluez. In the meantime I'll just patch it. I just wanted to make you aware of the edge case.

**Comment by bneijt** [comment]
Released the partial bugfix, and I'm closing this bug for now.

I don't think git support is something we need atm, because the best use-case for the lock package is currently if you have a private repository and want to pin deployments using pip in a production environment. That will probably not require git versions, but I leave it open for somebody to open an issue if they encounter the use-case and require it.
